### ISSUE TITLE
Update Gradle Dependencies

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/epicentre-android#5]
Update gradle dependencies with latest Material Design and all other libraries

**Comment by lucianofecampos** [comment]
Hi @prabhuomkar, can I pick this issue to do?

**Comment by prabhuomkar** [comment]
Yeah you can take this @lucianofecampos

**Comment by indracs97** [comment]
Can I take this and also what other libraries do you want?

**Comment by prabhuomkar** [comment]
Yes @indracs97 you can take this. If you send a PR first. I'll merge it :)

**Comment by indracs97** [comment]
@prabhuomkar Okay but should I migrate the whole project to AndroidX since it is recommended while switching to Material Design 2.0 standards.

**Comment by prabhuomkar** [comment]
Yeah you should do that :)

**Comment by indracs97** [comment]
Created a pull request #7

**Comment by indracs97** [comment]
Hey @prabhuomkar can you look into my PR #7 !

**Comment by prabhuomkar** [comment]
Thanks for your contribution @indracs97
