### ISSUE TITLE
Update README with Screenshots

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/epicentre-android#6]
**Tasks**:
- Clone and Run the app using Android Studio
- Capture screenshots of multiple all activities and fragments
- Save those screenshots in `images/screenshots` folder
- Create a table in README under new section `### Screenshots` and add those screenshots with proper name

**Comment by prabhuomkar** [comment]
Hey @indracs97 can you take this one too?

**Comment by Surya97** [comment]
Can I look into this?

**Comment by prabhuomkar** [comment]
Hey @Surya97 you can take this!

**Comment by Surya97** [comment]
Hey, @prabhuomkar I have cloned the repo and ran the application. It asks for Application endpoint and a secret code. What shall I enter there?
![image](https://user-images.githubusercontent.com/12216145/67626219-35a05f80-f7fd-11e9-8a64-91b7a1ab1990.png)

**Comment by prabhuomkar** [comment]
Youll have to setup Epicentre for that. Check out https://github.com/siesgstarena/Epicentre for installing instructions.

**Comment by Surya97** [comment]
@prabhuomkar I think switching the launcher activity is a nice idea. Will do that and take the screenshots.

**Comment by prabhuomkar** [comment]
Closing it since no updates.
